import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./_components/footer";
import Navbar from "./_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </head>
      <body>
        <Navbar></Navbar>
        <div className={`${inter.className} px-[10vw] py-[5vh]`}>
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}

//can add global components here e.g. navbar and footer
