import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./_components/footer";
import Navbar from "./_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "朴乐自然学习 | Pure Nature Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Navbar></Navbar>
        <div className={`${inter.className} px-[10vw] py-[5vh]`}>
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}

//can add global components here e.g. navbar and footer
